services:
    respondedorbot:
        container_name: respondedorbot
        restart: always
        read_only: true
        ports:
            - PORT:8080
        environment:
            - TELEGRAM_TOKEN=
            - REDIS_HOST=
            - REDIS_PORT=
            - REDIS_PASSWORD=
            - COINMARKETCAP_KEY=
            - ADMIN_CHAT_ID=
            - TELEGRAM_USERNAME=
            - CURRENT_FUNCTION_URL=
            - MAIN_FUNCTION_URL=
            - FRIENDLY_INSTANCE_NAME=
            - OPENROUTER_API_KEY=
            - GORDO_KEY=
        image: ghcr.io/astrovm/respondedorbot:master
